/*
Date :- 14 Sept 21
Name : Abhay Singh
Uid : 20BCS2966
*/

// hello world program without package.
class helloworld{  
    public static void main(String args[]){  
     System.out.println("Hello Java");  
    }  
} 
// one .class file would be generated by machine.


// hello world with package 

package com.abhaysingh;

public class helloworld{
	public static void main(String[] args) {

		System.out.println("Hello World");
	}
}
// one package folder would be generated by machine 

// for execution of package file 
/*
In CMD :
    -> javac -d . helloworld.java
    -> java com.abhaysingh.helloworld
*/
